name: 'PR - Deploy to Prod'
on:
  workflow_dispatch:
  merge_group:
  pull_request:
    paths-ignore:
      - '*.tfstate'
      - '.github/workflows/*'

permissions:
  contents: write
env:
  tf_version: 1.4.6
  tf_working_dir: .
  terrahelp_shasum: b086a87b7d98c4c84767836e897663ec7fa1ae678230a55041abdc817579a04f
jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }} 

      - name: test
        run: cat .git/branches/config
